### ISSUE TITLE
`Homepage` link on Nextcloud app listing goes to a 404

### ISSUE THREAD

**Issue by HammyHavoc** [julien-nc/phonetrack#24]
Just letting you know! Only the documentation links worked for me.

**Comment by K0-RR** [comment]
Bump. The issue is that the homepage link is https://github.com/julien-nc/phonetrack-oc and this repo name is "phonetrack"

**Comment by julien-nc** [comment]
This has been fixed. It will be effective after publishing the next release. Thanks for reporting this.
