### ISSUE TITLE
`Creation of dynamic property OCA\\PhoneTrack\\Activity\\PhonetrackProvider::$groupManager is deprecated at..`

### ISSUE THREAD

**Issue by HammyHavoc** [julien-nc/phonetrack#25]
I'm getting this error in my logs:

`{"reqId":"zDau0sgAsikZ2ospV7HZ","level":0,"time":"2023-10-29T12:47:05+00:00","remoteAddr":"REDACTED","user":"hammyhavoc","app":"PHP","method":"GET","url":"/ocs/v2.php/apps/notifications/api/v2/notifications","message":"Creation of dynamic property OCA\\PhoneTrack\\Activity\\PhonetrackProvider::$groupManager is deprecated at /config/www/nextcloud/apps/phonetrack/lib/Activity/PhonetrackProvider.php#59","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36","version":"27.1.3.2","data":{"app":"PHP"},"id":"653e544a96a06"}`

**Comment by julien-nc** [comment]
This is fixed and will be included in the next release.
