### ISSUE TITLE
Backends provided no user object at

### ISSUE THREAD

**Issue by louim-lbs** [julien-nc/phonetrack#26]
I have this error every day. I think it is related to the daily export (cronAutoExport). Though the export seems to work, I still get this error.
PhoneTrack v 0.7.6
Nextcloud v 27.1.3

[files] Erreur: OC\User\NoUserException: Backends provided no user object at <<closure>>

 0. <<closure>>
    OC\Files\Node\Root->getUserFolder()
 1. /app/www/public/lib/private/Files/Node/LazyFolder.php line 74
    call_user_func_array()
 2. /app/www/public/lib/private/Files/Node/LazyRoot.php line 40
    OC\Files\Node\LazyFolder->__call()
 3. /config/www/nextcloud/apps/files_versions/lib/Listener/FileEventsListener.php line 359
    OC\Files\Node\LazyRoot->getUserFolder()
 4. /config/www/nextcloud/apps/files_versions/lib/Listener/FileEventsListener.php line 201
    OCA\Files_Versions\Listener\FileEventsListener->getPathForNode()
 5. /config/www/nextcloud/apps/files_versions/lib/Listener/FileEventsListener.php line 108
    OCA\Files_Versions\Listener\FileEventsListener->write_hook()
 6. /app/www/public/lib/private/EventDispatcher/ServiceEventListener.php line 86
    OCA\Files_Versions\Listener\FileEventsListener->handle()
 7. /app/www/public/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 251
    OC\EventDispatcher\ServiceEventListener->__invoke()
 8. /app/www/public/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 73
    Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
 9. /app/www/public/lib/private/EventDispatcher/EventDispatcher.php line 94
    Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
10. /app/www/public/lib/private/EventDispatcher/EventDispatcher.php line 106
    OC\EventDispatcher\EventDispatcher->dispatch()
11. /app/www/public/lib/private/Files/Node/HookConnector.php line 112
    OC\EventDispatcher\EventDispatcher->dispatchTyped()
12. /app/www/public/lib/private/legacy/OC_Hook.php line 105
    OC\Files\Node\HookConnector->write()
13. /app/www/public/lib/private/Files/View.php line 1270
    OC_Hook::emit()
14. /app/www/public/lib/private/Files/View.php line 1144
    OC\Files\View->runHooks()
15. /app/www/public/lib/private/Files/View.php line 987
    OC\Files\View->basicOperation()
16. /app/www/public/lib/private/Files/Node/File.php line 116
    OC\Files\View->fopen()
17. /config/www/nextcloud/apps/phonetrack/lib/Service/SessionService.php line 402
    OC\Files\Node\File->fopen()
18. /config/www/nextcloud/apps/phonetrack/lib/Service/SessionService.php line 273
    OCA\PhoneTrack\Service\SessionService->export()
19. /config/www/nextcloud/apps/phonetrack/lib/Cron/AutoExport.php line 25
    OCA\PhoneTrack\Service\SessionService->cronAutoExport()
20. /app/www/public/lib/private/BackgroundJob/Job.php line 54
    OCA\PhoneTrack\Cron\AutoExport->run()
21. /app/www/public/lib/private/BackgroundJob/TimedJob.php line 60
    OC\BackgroundJob\Job->execute()
22. /app/www/public/cron.php line 152
    OC\BackgroundJob\TimedJob->execute()

at 2023-11-10T09:53:20+00:00

**Comment by julien-nc** [comment]
Hi, thanks for the bug report. It might be an issue in Nextcloud server.
I'm seeing this in the logs of an instance on my side too. But it stopped. The last I see is on December 11th 2023.
Have you upgraded Nextcloud to 28? Do you still see this exception in the logs?

**Comment by louim-lbs** [comment]
Hello,
I don't see this error anymore, the Nextcloud update seems to have done the job.
Thank you!
