### ISSUE TITLE
incompatible with nextcloud 28

### ISSUE THREAD

**Issue by GVLLIFESTYLE** [julien-nc/phonetrack#29]
Does not at all work anymore since nextcloud hub 7.

**Comment by carling-knock** [comment]
I'm on NC hub 7 since last night, too.
Latests PhoneTrack v.0.7.7 solved the issue for me, you may check updates in NC +Apps
Worked for me.

**Comment by dugite-code** [comment]
Just to add I needed to restart my Nextcloud docker container, presumably I could have gotten away with restarting the php process to clear any caching
