### ISSUE TITLE
Php cron job fails on Nextcloud 29.0.0 Beta 

### ISSUE THREAD

**Issue by noxxomix** [julien-nc/phonetrack#36]
Since upgrading I now notice that the cron job fails with the following:
Error: Class "OC\BackgroundJob\TimedJob" not found in /var/www/nextcloud/apps/phonetrack/lib/Cron/AutoExport.php:15

Nextcloud support inform me that the music app should move from OC to OCP in order to prevent this failure under Nextcloud 29.0.0.

**Comment by rcfa** [comment]
Same here. Not sure why the app is listed as compatible with version 29 in the app store

**Comment by fr3ddy-sudo** [comment]
Same here, with NC 29 RC4

`Error: Class "OC\BackgroundJob\TimedJob" not found in /var/www/nextcloud/apps/phonetrack/lib/Cron/AutoExport.php:15
Stack trace:
#0 /var/www/nextcloud/lib/composer/composer/ClassLoader.php(576): include()
#1 /var/www/nextcloud/lib/composer/composer/ClassLoader.php(427): Composer\Autoload\{closure}()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(126): ReflectionClass->__construct()
#4 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(146): OC\AppFramework\Utility\SimpleContainer->resolve()
#5 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(470): OC\AppFramework\Utility\SimpleContainer->query()
#6 /var/www/nextcloud/lib/private/ServerContainer.php(155): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#7 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(64): OC\ServerContainer->query()
#8 /var/www/nextcloud/lib/public/Server.php(55): OC\AppFramework\Utility\SimpleContainer->get()
#9 /var/www/nextcloud/lib/private/BackgroundJob/JobList.php(326): OCP\Server::get()
#10 /var/www/nextcloud/lib/private/BackgroundJob/JobList.php(235): OC\BackgroundJob\JobList->buildJob()
#11 /var/www/nextcloud/cron.php(163): OC\BackgroundJob\JobList->getNext()
#12 {main}
`

**Comment by mdwilst** [comment]
same issue here, Nextcloud Hub 8 (29.0.0 RC5):

Error: Class "OC\BackgroundJob\TimedJob" not found in /ssd/nextcloud/apps/phonetrack/lib/Cron/AutoExport.php:15
Stack trace:
#0 /ssd/nextcloud/lib/composer/composer/ClassLoader.php(576): include()
#1 /ssd/nextcloud/lib/composer/composer/ClassLoader.php(427): Composer\Autoload\{closure}()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 /ssd/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(126): ReflectionClass->__construct()
#4 /ssd/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(146): OC\AppFramework\Utility\SimpleContainer->resolve()
#5 /ssd/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(470): OC\AppFramework\Utility\SimpleContainer->query()
#6 /ssd/nextcloud/lib/private/ServerContainer.php(155): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#7 /ssd/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(64): OC\ServerContainer->query()
#8 /ssd/nextcloud/lib/public/Server.php(55): OC\AppFramework\Utility\SimpleContainer->get()
#9 /ssd/nextcloud/lib/private/BackgroundJob/JobList.php(326): OCP\Server::get()
#10 /ssd/nextcloud/lib/private/BackgroundJob/JobList.php(235): OC\BackgroundJob\JobList->buildJob()
#11 /ssd/nextcloud/cron.php(163): OC\BackgroundJob\JobList->getNext()
#12 {main}

**Comment by michz** [comment]
Same here for 29 stable version.

Others had similar problems, see for example:
https://github.com/nextcloud/richdocuments/pull/3527

**Comment by prolibre** [comment]
idem +1

**Comment by mr-wolf-gb** [comment]
i think same problem :

Stack Trace :
```
root@srv-nc:/var/www/html/nextcloud/data# sudo -u www-data php -f /var/www/html/nextcloud/cron.php
Error: Class "OC\BackgroundJob\TimedJob" not found in /var/www/html/nextcloud/apps/dropit/lib/BackgroundJob/CleanUpJob.php:34
Stack trace:
#0 /var/www/html/nextcloud/lib/composer/composer/ClassLoader.php(576): include()
#1 /var/www/html/nextcloud/lib/composer/composer/ClassLoader.php(427): Composer\Autoload\{closure}()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(126): ReflectionClass->__construct()
#4 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(146): OC\AppFramework\Utility\SimpleContainer->resolve()
#5 /var/www/html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(470): OC\AppFramework\Utility\SimpleContainer->query()
#6 /var/www/html/nextcloud/lib/private/ServerContainer.php(155): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#7 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(64): OC\ServerContainer->query()
#8 /var/www/html/nextcloud/lib/public/Server.php(55): OC\AppFramework\Utility\SimpleContainer->get()
#9 /var/www/html/nextcloud/lib/private/BackgroundJob/JobList.php(326): OCP\Server::get()
#10 /var/www/html/nextcloud/lib/private/BackgroundJob/JobList.php(235): OC\BackgroundJob\JobList->buildJob()
#11 /var/www/html/nextcloud/cron.php(163): OC\BackgroundJob\JobList->getNext()
#12 {main}
```

**Comment by prolibre** [comment]
@mr-wolf-gb Please note that there is indeed a problem with phonetrack but your logs correspond to a similar problem with the **dropit** application :-) have a nice day !
The cron problem is present in many applications.

**Comment by mr-wolf-gb** [comment]
> @mr-wolf-gb Please note that there is indeed a problem with phonetrack but your logs correspond to a similar problem with the **dropit** application :-) have a nice day !
> The cron problem is present in many applications.

Sorry I distinguished the problem and solved 😅

**Comment by michz** [comment]
https://github.com/julien-nc/phonetrack/releases/tag/v0.8.1 is released and works for me.

Thanks, @julien-nc !

**Comment by julien-nc** [comment]
You're welcome!

**Comment by bentolor** [comment]
I'm on phonetrack 0.8.1 on Nextcloud 29.0.0 in an Docker environmant, and still do receive this error. Any hints?

```
Error: Class "OC\BackgroundJob\TimedJob" not found in /var/www/html/custom_apps/phonetrack/lib/Cron/AutoExport.php:15
Stack trace:
#0 /var/www/html/lib/composer/composer/ClassLoader.php(576): include()
#1 /var/www/html/lib/composer/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/var/www/html/c...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('OCA\\PhoneTrack\\...')
#3 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(126): ReflectionClass->__construct('OCA\\PhoneTrack\\...')
#4 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(146): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\PhoneTrack\\...')
#5 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(470): OC\AppFramework\Utility\SimpleContainer->query('OCA\\PhoneTrack\\...')
#6 /var/www/html/lib/private/ServerContainer.php(155): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\PhoneTrack\\...')
#7 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(64): OC\ServerContainer->query('OCA\\PhoneTrack\\...')
#8 /var/www/html/lib/public/Server.php(55): OC\AppFramework\Utility\SimpleContainer->get('OCA\\PhoneTrack\\...')
#9 /var/www/html/lib/private/BackgroundJob/JobList.php(326): OCP\Server::get('OCA\\PhoneTrack\\...')
#10 /var/www/html/lib/private/BackgroundJob/JobList.php(235): OC\BackgroundJob\JobList->buildJob(Array)
#11 /var/www/html/cron.php(163): OC\BackgroundJob\JobList->getNext(true)
#12 {main}

```
