### ISSUE TITLE
Wrong links in Nextcloud Apps PhoneTrack page

### ISSUE THREAD

**Issue by siccovansas** [julien-nc/phonetrack#41]
The following two links are wrong when I open PhoneTrack in my Nextcloud's Apps page.

[Visit website ↗](https://github.com/julien-nc/phonetrack-oc)
[Report a bug ↗](https://github.com/julien-nc/phonetrack-oc/issues)

They link to the julien-nc/phonetrack-oc repo instead of julien-nc/phonetrack.

**Comment by julien-nc** [comment]
This is supposed to be fixed already. Which version of Phonetrack and which version of Nextcloud are you using?

**Comment by siccovansas** [comment]
I checked again and it is indeed fixed! I guess I checked before updating and it was fixed in the last update. Thx!
