### ISSUE TITLE
Problem with the menu link (nextcloud 29.0.0)

### ISSUE THREAD

**Issue by prolibre** [julien-nc/phonetrack#45]
Under nextcloud 29 the menu link is missing (but there is the icon). I have to enter the url (...)/index.php/apps/phonetrack/ to go to the application.

Here is what I have in source code (firefox) and you can see that the link is missing (**href=""**) !?

```
<li data-v-62f74e6b="" data-app-id="phonetrack" class="app-menu-entry">
<a data-v-62f74e6b="" href="" aria-label="Phonetrack" title="Phonetrack" class="">
<img data-v-62f74e6b="" src="/apps/phonetrack/img/app.svg" alt="">
 <div data-v-62f74e6b="" class="app-menu-entry--label">
Phonetrack
<!---->
</div>
</a>
</li>
```

I have the same problem with gpxpod (https://github.com/julien-nc/gpxpod/issues/46)

**Comment by prolibre** [comment]
I've just solved the problem by deactivating and reactivating the "fulltextsearch" application.

**Comment by jacotec** [comment]
@prolibre Awesome! This fixes the menu chaos in all of my 3 instances! Thanks!

**Comment by jacotec** [comment]
@prolibre ... unfortunately this does not fix it permanently. Other user, other browser and it's there again. So I need to disable the Fulltextsearch app for now. I'll file a bug there.

**Comment by prolibre** [comment]
@jacotec I've just updated nextcloud (29.0.1) and I've got the same problem again. But what's strange is that the missing link is only on "phonetrack" and "gpxpod" :-( 
I don't have any problems with the other applications.

**Comment by jacotec** [comment]
@prolibre There is a bunch more ... Memories, Polls and some more which I don't have in my mind anymore

**Comment by prolibre** [comment]
@jacotec I deactivated fulltextsearch then reactivated the application and it works again. Strange.

**Comment by prolibre** [comment]
Bug concerning fulltextsearch > https://github.com/nextcloud/fulltextsearch/issues/842
